name: mobile_gpt
description: OpenAI Chat-GPT and Dall-E 2.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.0.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 200
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 800
